INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('1','Inter','{"citta": "Milano", "stadio": "Giuseppe Meazza", "colore_bordo": "#000000", "colore_testo": "#0080ff", "colore_sfondo": "#000000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('2','Juventus','{"citta": "Torino", "stadio": "Allianz Stadium", "colore_bordo": "#000000", "colore_testo": "#ffffff", "colore_sfondo": "#000000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('3','Roma','{"citta": "Roma", "stadio": "Olimpico", "colore_bordo": "#ffd700", "colore_testo": "#aa0000", "colore_sfondo": "#ff8000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('4','Milan','{"citta": "Milano", "stadio": "Giuseppe Meazza", "colore_bordo": "#000000", "colore_testo": "#ff0000", "colore_sfondo": "#000000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('5','Fiorentina','{"citta": "Firenze", "stadio": "Artemio Franchi", "colore_bordo": "#ff0000", "colore_testo": "#ffffff", "colore_sfondo": "#8a2be2"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('6','Lazio','{"citta": "Roma", "stadio": "Olimpico", "colore_bordo": "#ffff00", "colore_testo": "#ffffff", "colore_sfondo": "#87ceeb"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('7','Torino','{"citta": "Torino", "stadio": "Olimpico Grande Torino", "colore_bordo": "#800000", "colore_testo": "#ffffff", "colore_sfondo": "#800000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('8','Napoli','{"citta": "Napoli", "stadio": "Diego Armando Maradona", "colore_bordo": "#00ffff", "colore_testo": "#ffffff", "colore_sfondo": "#00ffff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('9','Bologna','{"citta": "Bologna", "stadio": "Renato Dall''Ara", "colore_bordo": "#ff0000", "colore_testo": "#0080ff", "colore_sfondo": "#ff0000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('10','Sampdoria','{"citta": "Genova", "stadio": "Luigi Ferraris", "colore_bordo": "#000000", "colore_testo": "#ffffff", "colore_sfondo": "#0000ff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('11','Atalanta','{"citta": "Bergamo", "stadio": "Gewiss Stadium", "colore_bordo": "#000000", "colore_testo": "#000000", "colore_sfondo": "#0080c0"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('12','Genoa','{"citta": "Genova", "stadio": "Luigi Ferraris", "colore_bordo": "#ffff00", "colore_testo": "#0000ff", "colore_sfondo": "#ff0000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('13','Udinese','{"citta": "Udine", "stadio": "Bluenergy Stadium", "colore_bordo": "#ffff80", "colore_testo": "#ffffff", "colore_sfondo": "#000000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('14','Cagliari','{"citta": "Cagliari", "stadio": "Unipol Domus", "colore_bordo": "#000000", "colore_testo": "#0000ff", "colore_sfondo": "#ff8080"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('15','Verona','{"citta": "Verona", "stadio": "Marcantonio Bentegodi", "colore_bordo": "#ffff00", "colore_testo": "#0000ff", "colore_sfondo": "#ffff00"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('16','Bari','{"citta": "Bari", "stadio": "San Nicola", "colore_bordo": "#000000", "colore_testo": "#ff0000", "colore_sfondo": "#ffffff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('17','Vicenza','{"citta": "Vicenza", "stadio": "Romeo Menti", "colore_bordo": "#ffffff", "colore_testo": "#ff0000", "colore_sfondo": "#ffffff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('18','Palermo','{"citta": "Palermo", "stadio": "Renzo Barbera", "colore_bordo": "#ff80c0", "colore_testo": "#000000", "colore_sfondo": "#ff80c0"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('19','Parma','{"citta": "Parma", "stadio": "Ennio Tardini", "colore_bordo": "#ffff00", "colore_testo": "#000000", "colore_sfondo": "#ffffff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('20','Triestina','{"citta": "Trieste", "stadio": "Nereo Rocco", "colore_bordo": "#ff0000", "colore_testo": "#ffffff", "colore_sfondo": "#ff0000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('21','Brescia','{"citta": "Brescia", "stadio": "Mario Rigamonti", "colore_bordo": "#0073e6", "colore_testo": "#ffffff", "colore_sfondo": "#0073e6"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('22','Lecce','{"citta": "Lecce", "stadio": "Via del Mare", "colore_bordo": "#ffd700", "colore_testo": "#ff0000", "colore_sfondo": "#ffd700"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('23','SPAL','{"citta": "Ferrara", "stadio": "Paolo Mazza", "colore_bordo": "#0080ff", "colore_testo": "#ffffff", "colore_sfondo": "#0080ff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('24','Livorno','{"citta": "Livorno", "stadio": "Stadio Armando Picchi", "colore_bordo": "#804040", "colore_testo": "#ffffff", "colore_sfondo": "#804040"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('25','Catania','{"citta": "Catania", "stadio": "Angelo Massimino", "colore_bordo": "#00ffff", "colore_testo": "#ff0000", "colore_sfondo": "#00ffff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('26','Chievo','{"citta": "Verona", "stadio": "Marcantonio Bentegodi", "colore_bordo": "#ffff00", "colore_testo": "#0000ff", "colore_sfondo": "#ffff00"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('27','Empoli','{"citta": "Empoli", "stadio": "Carlo Castellani", "colore_bordo": "#0000ff", "colore_testo": "#ffffff", "colore_sfondo": "#0000ff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('28','Ascoli','{"citta": "Ascoli", "stadio": "Cino e Lillo Del Duca", "colore_bordo": "#ff0000", "colore_testo": "#000000", "colore_sfondo": "#ffffff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('29','Padova','{"citta": "Padova", "stadio": "Euganeo", "colore_bordo": "#ff0000", "colore_testo": "#ffffff", "colore_sfondo": "#ff0000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('30','Como','{"citta": "Como", "stadio": "Giuseppe Sinigaglia", "colore_bordo": "#ffffff", "colore_testo": "#0000ff", "colore_sfondo": "#ffffff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('31','Venezia','{"citta": "Venezia", "stadio": "Pier Luigi Penzo", "colore_bordo": "#000000", "colore_testo": "#ff8000", "colore_sfondo": "#008080"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('32','Alessandria','{"citta": "Alessandria", "stadio": "Giuseppe Moccagatta", "colore_bordo": "#ff0000", "colore_testo": "#000000", "colore_sfondo": "#808080"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('33','Cesena','{"citta": "Cesena", "stadio": "Orogel Stadium-Dino Manuzzi", "colore_bordo": "#ffffff", "colore_testo": "#000000", "colore_sfondo": "#ffffff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('34','Modena','{"citta": "Modena", "stadio": "Alberto Braglia", "colore_bordo": "#ffff00", "colore_testo": "#0000ff", "colore_sfondo": "#ffff00"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('35','Novara','{"citta": "Novara", "stadio": "Silvio Piola", "colore_bordo": "#ff0000", "colore_testo": "#ffffff", "colore_sfondo": "#0080ff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('36','Perugia','{"citta": "Perugia", "stadio": "Renato Curi", "colore_bordo": "#ff0000", "colore_testo": "#ffffff", "colore_sfondo": "#ff0000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('37','Pro Patria','{"citta": "Busto Arsizio", "stadio": "Carlo Speroni", "colore_bordo": "#ffffff", "colore_testo": "#0000ff", "colore_sfondo": "#ffffff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('38','Sassuolo','{"citta": "Sassuolo", "stadio": "Mapei Stadium", "colore_bordo": "#008000", "colore_testo": "#000000", "colore_sfondo": "#008000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('39','Foggia','{"citta": "Foggia", "stadio": "Pino Zaccheria", "colore_bordo": "#ff0000", "colore_testo": "#000000", "colore_sfondo": "#ff0000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('40','Avellino','{"citta": "Avellino", "stadio": "Partenio-Adriano Lombardi", "colore_bordo": "#008000", "colore_testo": "#ffffff", "colore_sfondo": "#008000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('41','Reggina','{"citta": "Reggio Calabria", "stadio": "Oreste Granillo", "colore_bordo": "#800000", "colore_testo": "#ffffff", "colore_sfondo": "#800000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('42','Siena','{"citta": "Siena", "stadio": "Artemio Franchi", "colore_bordo": "#ffffff", "colore_testo": "#000000", "colore_sfondo": "#ffffff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('43','Cremonese','{"citta": "Cremona", "stadio": "Giovanni Zini", "colore_bordo": "#ff0000", "colore_testo": "#ffffff", "colore_sfondo": "#ff0000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('44','Lucchese','{"citta": "Lucca", "stadio": "Porta Elisa", "colore_bordo": "#ff0000", "colore_testo": "#000000", "colore_sfondo": "#ff0000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('45','Piacenza','{"citta": "Piacenza", "stadio": "Leonardo Garilli", "colore_bordo": "#ff0000", "colore_testo": "#ffffff", "colore_sfondo": "#ff0000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('46','Sampierdarenese','{"citta": "Genova", "stadio": "Luigi Ferraris", "colore_bordo": "#ff0000", "colore_testo": "#000000", "colore_sfondo": "#ffffff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('47','Catanzaro','{"citta": "Catanzaro", "stadio": "Nicola Ceravolo", "colore_bordo": "#ffff00", "colore_testo": "#ff0000", "colore_sfondo": "#ffff00"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('48','Mantova','{"citta": "Mantova", "stadio": "Danilo Martelli", "colore_bordo": "#ffffff", "colore_testo": "#ff0000", "colore_sfondo": "#ffffff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('49','Pescara','{"citta": "Pescara", "stadio": "Adriatico", "colore_bordo": "#ffffff", "colore_testo": "#00ffff", "colore_sfondo": "#ffffff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('50','Pisa','{"citta": "Pisa", "stadio": "Arena Garibaldi", "colore_bordo": "#000000", "colore_testo": "#ffffff", "colore_sfondo": "#0000ff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('51','Varese','{"citta": "Varese", "stadio": "Franco Ossola", "colore_bordo": "#ffffff", "colore_testo": "#ff0000", "colore_sfondo": "#ffffff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('52','Pro Vercelli','{"citta": "Vercelli", "stadio": "Silvio Piola", "colore_bordo": "#ffffff", "colore_testo": "#000000", "colore_sfondo": "#ffffff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('53','Messina','{"citta": "Messina", "stadio": "San Filippo-Franco Scoglio", "colore_bordo": "#ffffff", "colore_testo": "#ffff00", "colore_sfondo": "#ff0000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('54','Salernitana','{"citta": "Salerno", "stadio": "Arechi", "colore_bordo": "#800000", "colore_testo": "#ffffff", "colore_sfondo": "#800000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('55','Casale','{"citta": "Casale Monferrato", "stadio": "Natale Palli", "colore_bordo": "#000000", "colore_testo": "#ffffff", "colore_sfondo": "#000000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('56','Crotone','{"citta": "Crotone", "stadio": "Ezio Scida", "colore_bordo": "#ff0000", "colore_testo": "#0000ff", "colore_sfondo": "#ff0000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('57','Frosinone','{"citta": "Frosinone", "stadio": "Benito Stirpe", "colore_bordo": "#ffff00", "colore_testo": "#0000ff", "colore_sfondo": "#ffff00"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('58','Lecco','{"citta": "Lecco", "stadio": "Rigamonti-Ceppi", "colore_bordo": "#ffffff", "colore_testo": "#00ffff", "colore_sfondo": "#0000ff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('59','Legnano','{"citta": "Legnano", "stadio": "Giovanni Mari", "colore_bordo": "#8080ff", "colore_testo": "#ffffff", "colore_sfondo": "#8080ff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('60','Monza','{"citta": "Monza", "stadio": "U-Power Stadium", "colore_bordo": "#ff0000", "colore_testo": "#ffffff", "colore_sfondo": "#ff0000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('61','Reggiana','{"citta": "Reggio Emilia", "stadio": "Mapei Stadium", "colore_bordo": "#ffff00", "colore_testo": "#ffffff", "colore_sfondo": "#800000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('62','Spezia','{"citta": "La Spezia", "stadio": "Alberto Picco", "colore_bordo": "#ffffff", "colore_testo": "#000000", "colore_sfondo": "#ffffff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('63','Ancona','{"citta": "Ancona", "stadio": "Del Conero", "colore_bordo": "#ffffff", "colore_testo": "#ff0000", "colore_sfondo": "#ffffff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('64','Benevento','{"citta": "Benevento", "stadio": "Ciro Vigorito", "colore_bordo": "#ffd700", "colore_testo": "#ff0000", "colore_sfondo": "#ffd700"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('65','Ternana','{"citta": "Terni", "stadio": "Libero Liberati", "colore_bordo": "#008040", "colore_testo": "#ff0000", "colore_sfondo": "#008040"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('66','Carpi','{"citta": "Carpi", "stadio": "Sandro Cabassi", "colore_bordo": "#ffffff", "colore_testo": "#ff0000", "colore_sfondo": "#ffffff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('67','Pistoiese','{"citta": "Pistoia", "stadio": "Marcello Melani", "colore_bordo": "#ff8000", "colore_testo": "#ffffff", "colore_sfondo": "#ff8000"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('68','Treviso','{"citta": "Treviso", "stadio": "Omobono Tenni", "colore_bordo": "#80ffff", "colore_testo": "#ffffff", "colore_sfondo": "#80ffff"}');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('69','Taranto','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('70','Cosenza','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('71','Sambenedettese','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('72','Cittadella','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('73','Arezzo','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('74','Fanfulla','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('75','Vigevano','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('76','Marzotto Valdagno','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('77','Prato','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('78','AlbinoLeffe','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('79','Rimini','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('80','Ravenna','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('81','Siracusa','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('82','Brindisi','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('83','Fidelis Andria','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('84','Grosseto','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('85','Juve Stabia','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('86','Seregno','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('87','Viareggio','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('88','Virtus Entella','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('89','Campobasso','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('90','Potenza','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('91','Savona','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('92','Trapani','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('93','Barletta','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('94','Latina','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('95','Monfalcone','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('96','Pavia','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('97','Pro Sesto','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('98','Virtus Lanciano','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('99','Carrarese','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('100','Cavese','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('101','Derthona','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('102','Grion Pola','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('103','L’Aquila','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('104','Nocerina','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('105','Piombino','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('106','Pordenone','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('107','Sanremese','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('108','Savoia','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('109','Südtirol','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('110','Acireale','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('111','Biellese','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('112','Casertana','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('113','Castel di Sangro','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('114','Crema','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('115','La Dominante','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('116','Fiumana','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('117','Gallaratese','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('118','Gubbio','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('119','Licata','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('120','Pro Gorizia','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('121','Rieti','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('122','Scafatese','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('123','Suzzara','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('124','Trani','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('125','Vogherese','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('126','Albatrastevere','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('127','Alzano Virescit','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('128','Arsenale Taranto','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('129','Bolzano','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('130','Centese','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('131','Feralpisalò','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('132','Fermana','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('133','Forlì','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('134','Gallipoli','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('135','Maceratese','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('136','Magenta','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('137','Massese','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('138','MATER','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('139','Matera','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('140','Mestre','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('141','Molinella','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('142','Portogruaro','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('143','Sestrese','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('144','Sorrento','[]');
INSERT IGNORE INTO `squadre` (`id`,`nome`,`params`) VALUES ('145','Vita Nova','[]');
